id: P1B040F72
initial_creation_type: ocr
source_metadata:
  volumes:
    05380b5cf2f24f96a66723f38e73e06c:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བཅོམ་ལྡན་འདས་ལ་བསྟོད་པ་དཔལ་རྡོ་རྗེ་འཛིན་གྱི་དབྱངས་ཀྱི་རྒྱ་ཆེར་བཤད་པ།
      total_pages: 1539
      volume_number: 1
